### ISSUE TITLE
Raiser's Edge NXT is has the wrong background colour for non modern-theme

### ISSUE THREAD

**Issue by ZaneGeiser** [blackbaud/skyux#2338]
# Problem Description
Looking at any of our Raiser's Edge NXT Page Addins, the Background colour is showing incorrectly for non modern-theme applicaitons. (which is all of Raiser's Edge at the moment.)

On the Host page there is a CSS for the HTML body element:
```
body:not(.sky-theme-modern) {
    background-color: #fff;
}
```

It should be:
```
body:not(.sky-theme-modern) {
    background-color: #eeeeef;
}
```

The reason for raising this request is that it causes NXT Page Addins that use SkyUX to appear with a harsh end to the page like this:
![Screenshot 2024-05-30 at 2 44 27 PM](https://github.com/blackbaud/skyux/assets/57169901/fd7df27d-b2f7-4963-ba30-e3c454738589)

# To Fix
A quick search through the code repo indicates that the change probably just needs to be made in two places:

1. https://github.com/blackbaud/skyux/blob/de7a443b143f9c1b8704b8b6be6815a6e952665c/libs/components/pages/src/lib/modules/page/page-theme-adapter.service.ts#L27
2. https://github.com/blackbaud/skyux/blob/de7a443b143f9c1b8704b8b6be6815a6e952665c/libs/components/layout/src/lib/modules/page/page-theme-adapter.service.ts#L27

[AB#2938835](https://dev.azure.com/blackbaud/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/2938835)

**Comment by ZaneGeiser** [comment]
Hi Team,

As an alternative, do you know of a way that we can enable our content to grow to the height of the screen?
What if the Page Add-in iframe set it's height to the be the height of the screen?
```
.bb-sky-addin-host-addin-wrapper iframe {
    display: block;
    height: calc(100vh - 74px);
    width: 100%;
}
```

**Comment by ZaneGeiser** [comment]
Hi @Blackbaud-PaulCrowder,

Hope you are well. Have you had chance to consider this issue? Wondering what you think about moving forward with it?

Kind regards,
Zane

**Comment by Blackbaud-PaulCrowder** [comment]
The host page has a white background because it uses the [SKY UX page component](https://developer.blackbaud.com/skyux/components/page?docs-active-tab=design). Your page should also use this component to wrap the contents of the add-in. Having said that, I believe that will still produce a gray background for the tile dashboard which may still result in the white area you see beneath the add-in, but should at least make the background of the page heading the correct (white) color.

As for making the add-in iframe the height of the screen, that would be a question for the SKY API team. I'll reach out to them with a link to this issue.

**Comment by michael-tims** [comment]
Hi @ZaneGeiser - we do have a known issue for the SKY API Team (owning team of [page add-ins](https://developer.blackbaud.com/skyapi/docs/addins/get-started/page-addins)) for the vertical sizing of page add-ins.  Since this is not a SKY UX problem, are you able to log a bug with Blackbaud Support?  Logging the bug will help you in tracking the status for a fix and will help us to push it along internally.  Thanks!

**Comment by ZaneGeiser** [comment]
Hi all,

@michael-tims, That makes sense and thank you for suggesting. I have raised the issue with case number 019759629.

@Blackbaud-PaulCrowder, Thank you for the suggestion to use the Page Component. I have implemented this but you're right that it doesn't fix the issue with the tile dashboard background colour. I'm considering switching our apps to use boxes instead of tiles as that would fix the issue with the background colour. Plus, boxes probably make more sense as we own all of the content on our page and this would give us more control over the layout than the tile dashboard does. 
I suppose the other thing that would fix my issue with the background colour would be switching to modern theme. But that still seems like it is a long ways off for Raiser's Edge.
