### ISSUE TITLE
<sky-ag-grid-wrapper> causes ngbTooltips to freeze the entire application

### ISSUE THREAD

**Issue by ZaneGeiser** [blackbaud/skyux#2899]
Hey team, 
Bit of a weird one here but I'm hoping that y'all might know where we have gone wrong.

https://github.com/user-attachments/assets/7389964d-2b30-4956-9b83-8e190213cca0

We recently introduced skyux/ag-grid into our app and are phasing our skyux/grids. There is an issue when we have a <sky-ag-grid-wrapper> rendered within the app, and then go to hover over a different element within the app that makes use of a ngbTooltip from @ng-bootstrap/ng-bootstrap, it causes the entire app to freeze and become un-responsive. 

For example
```
// componentA HTML 
<button
      type="button"
      class="sky-btn sky-btn-default"
      ngbTooltip="refresh"
      (click)="refresh()"
  >
      <sky-icon icon="refresh" />
 </button>
```

```
// componentB HTML
<sky-ag-grid-wrapper>
    <ag-grid-angular [gridOptions]="gridOptions" [rowData]="campaignList" />
</sky-ag-grid-wrapper>
```

The furthest I have made to narrowing down the issue is that if I comment out the <sky-ag-grid-wrapper> and use ag-grid-angular without the wrapper, with no other changes, then the issue no longer occurs. What is it with <sky-ag-grid-wrapper> that could be causing this issue.

**Troubleshooting steps taken:**
- upgrade and downgrade skyux, angular, popper, and bootstrap dependencies.
- test on all browsers (chrome, firefox, safari, arc, brave, edge)
- update my implementation to use ChangeDetectionStrategy.OnPush
- Reviews of any missing imports of related modules. (I don't think I'm missing any imports)

**Relevant dependency version that I am using:**
        "@angular/core": "18.2.10",
        "@ng-bootstrap/ng-bootstrap": "17.0.1",
        "@popperjs/core": "2.11.8",
        "@skyux/ag-grid": "11.20.0",

**Comment by johnhwhite** [comment]
@ZaneGeiser can you create a [Stackblitz](https://stackblitz.com/) that recreates the issue? You can start with our [data grid code example](https://developer.blackbaud.com/skyux/components/data-grid?docs-active-tab=code-examples) or build your own.

**Comment by ZaneGeiser** [comment]
@johnhwhite, that is an excellent idea! Here is a working example.

https://stackblitz.com/edit/angular-fj1yce?file=src%2Fapp%2Fdemo.component.html

**Comment by johnhwhite** [comment]
Created bug AB#3148276 — the team will review it and talk through next steps.

**Comment by johnhwhite** [comment]
@ZaneGeiser I looked into the issue. I'm seeing an infinite loop where ngbTooltips uses [`afterRender`](https://angular.dev/api/core/afterRender) to update the popover position in [`tooltip.ts`](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/tooltip/tooltip.ts#L259) and ends up in a change detection loop. It's odd that it only happens with `<sky-ag-grid-wrapper>`, but the error is happening in their code.

Also worth noting, we recommend not using tooltips because they are generally not accessible, and we have guidance for providing [call-out information](https://developer.blackbaud.com/skyux/design/guidelines/call-out-info) and [user assistance](https://developer.blackbaud.com/skyux/design/guidelines/user-assistance) using alternative patterns.

Closing.
